name: Node.js CI

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Setup Node.js v14
      uses: actions/setup-node@v2
      with:
        node-version: 14.x

    - name: Setup npm cache
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}-${{ matrix.browser }}
        restore-keys: |
          ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright browsers
      run: npx playwright install-deps ${{ matrix.browser }}

    - name: Build the library
      run: npm run build --if-present

    - name: Run tests
      run: npm test
      env:
        BROWSER: ${{ matrix.browser }}
